### ISSUE TITLE
can't develop docs w/instructions in readme

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/workers-docs#896]
```console
$ git clone git@github.com:cloudflare/workers-docs.git
success
```

```console
$ cd workers-docs/workers-docs
success
```

```console
$ yarn
success
```

```console
$ yarn start
yarn run v1.22.4
$ npm run develop
npm WARN lifecycle The node binary used for scripts is /var/folders/xw/4ttxd3d12t79cv0cb78gwhzc0000gn/T/yarn--1591905989063-0.8009032233358093/node but npm is using /Users/averyharnish/.nvm/versions/node/v13.1.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> cloudflare-workers-docs@1.0.0 develop /Users/averyharnish/Documents/work/workers-docs/workers-docs
> gatsby develop -p 1313

/Users/averyharnish/Documents/work/workers-docs/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Package exports for '/Users/averyharnish/Documents/work/workers-docs/node_modules/clipboardy' do not define a '.' subpath
    at applyExports (internal/modules/cjs/loader.js:485:15)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/averyharnish/Documents/work/workers-docs/node_modules/gatsby-cli/lib/create-cli.js:24:42)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! cloudflare-workers-docs@1.0.0 develop: `gatsby develop -p 1313`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the cloudflare-workers-docs@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/averyharnish/.npm/_logs/2020-06-11T20_06_30_987Z-debug.log
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by EverlastingBugstopper** [comment]
had to upgrade to node v14.4.0 😄
